### ISSUE TITLE
Parsing nested settings broken?

### ISSUE THREAD

**Issue by SthPhoenix** [pydantic/pydantic-settings#125] opened 2023-07-12 19:26 UTC
Hi! I have recently updated to newer pydantic==2.0.2, which caused me to move to pydantic-settings for BaseSettings class.
And it seems that new version have broken some logic.

Here is test `.env` file:

```env
VAR1=main111
SUB1_VARIABLE1=sub111
```

Here is example using `pydantic.v1.env_settings`:
```python
from pydantic.v1.env_settings import BaseSettings


class BaseSettingsMod(BaseSettings):

    class Config:
        env_file='.env'

class Sub1(BaseSettingsMod):
    variable1: str = 'sub1'

    class Config:
        env_prefix = 'SUB1_'

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = 'main1'

settings = Settings()

print(settings.json(indent=2))
```

Result of print statement:
```json
{
  "sub1": {
    "variable1": "sub111"
  },
  "var1": "main111"
}
```

But if I try to use `pydantic_settings.BaseSettings`:

```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class BaseSettingsMod(BaseSettings):

    model_config = SettingsConfigDict(
        env_file='.env'
    )

class Sub1(BaseSettingsMod):
    var1: str = 'sub1'

    model_config = SettingsConfigDict(
        env_prefix = 'SUB1_'
    )

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = 'main1'

settings = Settings()
print(settings.model_dump_json(indent=2))
```

I got following traceback:

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/scratch/check_settings.py", line 42, in <module>
    class Settings(BaseSettingsMod):
  File "/home/user/PycharmProjects/scratch/check_settings.py", line 43, in Settings
    sub1: Sub1 = Sub1()
  File "/usr/local/lib/python3.10/dist-packages/pydantic_settings/main.py", line 62, in __init__
    **__pydantic_self__._settings_build_values(
  File "/usr/local/lib/python3.10/dist-packages/pydantic_settings/main.py", line 150, in _settings_build_values
    return deep_update(*reversed([source() for source in sources]))
  File "/usr/local/lib/python3.10/dist-packages/pydantic_settings/main.py", line 150, in <listcomp>
    return deep_update(*reversed([source() for source in sources]))
  File "/usr/local/lib/python3.10/dist-packages/pydantic_settings/sources.py", line 583, in __call__
    first_key, *_ = env_name_without_prefix.split(self.env_nested_delimiter)
ValueError: not enough values to unpack (expected at least 1, got 0)
```

Moreover, if I try to change code for more default pydantic behavior (double underscore for nested args):

```env
VAR1=main111
SUB1__VARIABLE1=sub111
```

```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class BaseSettingsMod(BaseSettings):

    model_config = SettingsConfigDict(
        env_file='.env'
    )

class Sub1(BaseSettingsMod):
    variable1: str = 'sub1'

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = 'main1'

settings = Settings()
print(settings.model_dump_json(indent=2))
```

I got following traceback:

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/scratch/check_settings.py", line 39, in <module>
    class Settings(BaseSettingsMod):
  File "/home/user/PycharmProjects/scratch/check_settings.py", line 40, in Settings
    sub1: Sub1 = Sub1()
  File "/usr/local/lib/python3.10/dist-packages/pydantic_settings/main.py", line 61, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Sub1
var1
  Extra inputs are not permitted [type=extra_forbidden, input_value='main111', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/extra_forbidden
sub1__variable1
  Extra inputs are not permitted [type=extra_forbidden, input_value='sub111', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/extra_forbidden

Process finished with exit code 1

```

Selected Assignee: @dmontagu

**Comment by hramezani** [comment] 2023-07-12 19:45
Thanks @SthPhoenix for reporting this 🙏 

I think it got fixed in the `main` branch(but hasn't deployed yet).
Could you please install `pydantic-settings` from the `main` branch and test it?

**Comment by SthPhoenix** [comment] 2023-07-12 20:46
> Thanks @SthPhoenix for reporting this pray
> 
> I think it got fixed in the `main` branch(but hasn't deployed yet). Could you please install `pydantic-settings` from the `main` branch and test it?

It works a bit better - providing both  `env_prefix` and `env_nested_delimiter` seems to work at first, but:
1. Omiting `env_prefix` leads to `Extra inputs are not permitted`
2. Changing `env_prefix` to `SUB2`, still populates Sub1.variable1 with value of `SUB1__VARIABLE1=sub111` 
3. Omiting `env_nested_delimiter` leads to `Extra inputs are not permitted`
4. Adding ANY extra variable to `.env` file leads to `Extra inputs are not permitted`

**Comment by hramezani** [comment] 2023-07-12 21:36
`Settings` inherits from `BaseSettingsMod` and you didn't define `env_prefix` in `BaseSettingsMod`.

It doesn't use `env_prefix='NONE__'` because it has been defined in `Sub1` and in your example your are instantiating `Settings`.

**Comment by SthPhoenix** [comment] 2023-07-13 05:25
> `Settings` inherits from `BaseSettingsMod` and you didn't define `env_prefix` in `BaseSettingsMod`.
> 
> It doesn't use `env_prefix='NONE__'` because it has been defined in `Sub1` and in your example your are instantiating `Settings`.

In older pydantic `env_prefix` defined inside specific subclass overrides settings of base class. 

But in this specific example main problem is that it populates `Sub1.variable1` with any `VARIABLE1` in env file, no matter what the prefix is. It seems that actual prefix value is just ignored.
Also as I stated before, any additional variable in env file, not defined in model causes `Extra inputs are not permitted`.

**Comment by hramezani** [comment] 2023-07-13 07:41
> But in this specific example main problem is that it populates Sub1.variable1 with any VARIABLE1 in env file, no matter what the prefix is. It seems that actual prefix value is just ignored.

because you have defined default values for fields in `Settings`.

> Also as I stated before, any additional variable in env file, not defined in model causes Extra inputs are not permitted.

Because in `pydantic-settings` by default `extra='forbid`.

**Comment by SthPhoenix** [comment] 2023-07-13 10:42
Ok, I have added `extra = 'allow'` to basemodel.

My `.env` file is as follows:
```env
VAR1=main111
SUB1__VARIABLE1=sub111
SUB2__VARIABLE2=sub222
SUB3__VARIABLE1=sub333
```

Here is reference code with older BaseSettings:

```python
from pydantic.v1.env_settings import BaseSettings

class BaseSettingsMod(BaseSettings):
    class Config:
        env_file = '.env'
        extra = 'allow'

class Sub1(BaseSettingsMod):
    variable1: str = ''
    class Config:
        env_prefix = 'SUB1__'

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = ''

settings = Settings()

print(settings.json(indent=2))
```

Here is reference, expected output of the code above:
```json
{
  "sub1": {
    "variable1": "sub111"
  },
  "var1": "main111"
}
```

Now I move to pydantic_settings.BaseSettings:
```python
from pydantic_settings import BaseSettings

class BaseSettingsMod(BaseSettings):
    class Config:
        env_file = '.env'
        extra = 'allow'

class Sub1(BaseSettingsMod):
    variable1: str = ''
    class Config:
        env_prefix = 'SUB1__'

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = ''

settings = Settings()

print(settings.model_dump_json(indent=2))
```
And here's an output:

```json
{
  "sub1": {
    "variable1": "sub111"
  },
  "var1": "main111",
  "sub1__variable1": "sub111",
  "sub2__variable2": "sub222",
  "sub3__variable1": "sub333"
}
```

As you can see now the model prints all the arguments, even if not described in model.
While older version reads only arguments in model.

Now I remove `env_prefix = 'SUB1__'` from class `Sub1`:

```python
from pydantic_settings import BaseSettings

class BaseSettingsMod(BaseSettings):
    class Config:
        env_file = '.env'
        extra = 'allow'

class Sub1(BaseSettingsMod):
    variable1: str = ''

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = ''

settings = Settings()

print(settings.model_dump_json(indent=2))
```
Which leads to:

```json
{
  "sub1": {
    "variable1": "",
    "var1": "main111",
    "sub1__variable1": "sub111",
    "sub2__variable2": "sub222",
    "sub3__variable1": "sub333"
  },
  "var1": "main111",
  "sub1__variable1": "sub111",
  "sub2__variable2": "sub222",
  "sub3__variable1": "sub333"
}
```

And now I add `env_nested_delimiter='__'` to class `BaseSettingsMod`:

```python
from pydantic_settings import BaseSettings

class BaseSettingsMod(BaseSettings):
    class Config:
        env_file = '.env'
        extra = 'allow'
        env_nested_delimiter = '__'

class Sub1(BaseSettingsMod):
    variable1: str = ''

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = ''

settings = Settings()

print(settings.model_dump_json(indent=2))
```

New output:
```json
{
  "sub1": {
    "variable1": "sub111",
    "var1": "main111",
    "sub1": "sub111",
    "sub2": "sub222",
    "sub3": "sub333"
  },
  "var1": "main111",
  "sub2": "sub222",
  "sub3": "sub333"
}
```

And now with `env_nested_delimiter='__'` and `env_prefix = 'SUB1__'`:

```python
from pydantic_settings import BaseSettings

class BaseSettingsMod(BaseSettings):
    class Config:
        env_file = '.env'
        extra = 'allow'
        env_nested_delimiter = '__'

class Sub1(BaseSettingsMod):
    variable1: str = ''
    class Config:
        env_prefix = 'SUB1__'

class Settings(BaseSettingsMod):
    sub1: Sub1 = Sub1()
    var1: str = ''

settings = Settings()

print(settings.model_dump_json(indent=2))
```

```json
{
  "sub1": {
    "variable1": "sub111"
  },
  "var1": "main111",
  "sub2": "sub222",
  "sub3": "sub333"
}
```

As you can see I wasn't able to reproduce behaviour of old pydantic.BaseSettings

**Comment by hramezani** [comment] 2023-07-13 11:06
You can reproduce the old behavior by setting the `extra='ignore'`

**Comment by SthPhoenix** [comment] 2023-07-13 11:23
> You can reproduce the old behavior by setting the `extra='ignore'`

Yes, thanks! That seems to work. 

I think it might be useful to highlight it in settings management documentation.

**Comment by hramezani** [comment] 2023-07-13 12:02
Actually, we already have documented this in the [dotenv section of pydantic-settings doc](https://docs.pydantic.dev/latest/usage/pydantic_settings/#dotenv-env-support)

Also, we have doc for [extra attributes](https://docs.pydantic.dev/latest/usage/model_config/#extra-attributes) as well.

**Comment by SthPhoenix** [comment] 2023-07-13 13:10
Yes, but they both are misleading:
1. In dotenv settings it states that it may throw errors when extra explicitly set to forbid,  which may lead you to conclusion that it's not default behavior.
2.  In extra attributes section its explicitly stated that default value is `ignore`, while it turned out that its `forbid` right now

**Comment by hramezani** [comment] 2023-07-13 13:13
@SthPhoenix it would be great if you can open a PR and improve it. Otherwise, I will close it.

**Closed** 2023-07-13 13:15 UTC
Labels: unconfirmed

**Comment by SthPhoenix** [comment] 2023-07-13 18:28
@hramezani I have opened a PR, but I can't figure out why it fails some tests in CI.

**Comment by hramezani** [comment] 2023-07-13 21:21
@SthPhoenix Thanks for the PR. It's because of the code format in the doc.
I've fixed it.
