### ISSUE TITLE
AzureKeyVaultSettingsSource ignoring SettingsSource Priority

### ISSUE THREAD

**Issue by DavidRR-F** [pydantic/pydantic-settings#412] opened 2024-09-19 21:10 UTC
I am trying to use the AzureKeyVaultSettingSource in my BaseSettings class configuration as specified in the [docs](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#azure-key-vault). 

I am running into an issue were, if I have an environment variable referenced in the class whose key is defined with an underscore `FOO_BAR`, a SettingsError as thrown by AzureKeyVaultSetttingSource rather than the key value being initialized by the env_settings which is configured to have a higher priority.

I know azure keyvault does not support underscores in secret names so this is most likely the source of the error, but I figured that source priority would initialize the environment variables first so the azure source would not try and grab that value.

## Example:
python==3.10
pydantic-settings==2.5.2
pydantic==2.9.2
azure-identity==1.17.1

```python
from pydantic_settings import (
    AzureKeyVaultSettingsSource,
    BaseSettings,
    PydanticBaseSettingsSource
)
from pydantic import Field, computed_field
from azure.identity import DefaultAzureCredential
from typing import Tuple, Type
import os

class Settings(BaseSettings):
    FOO: str # azure key vault value
    FOO_BAR: str # environment variable

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        az_key_vault_settings = AzureKeyVaultSettingsSource(
            settings_cls,
            os.environ.get("AZURE_KEY_VAULT_URL"),
            DefaultAzureCredential(),
        )
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            file_secret_settings,
            az_key_vault_settings,
        )

settings = Settings()

print(setting.FOO, setting.FOO_BAR)
```

### Error

```bash
Settings Error: pydantic_settings.sources.SettingsError: error getting value for field "FOO_BAR" from source "AzureKeyVaultSettingsSource"
```

Have I misconfigured/misunderstood something?

Does each setting iterate through each key independantly regardless of priority?

Thanks in advance! 😊

**Comment by hramezani** [comment] 2024-09-20 13:12
Thanks @DavidRR-F for reporting this issue.

> Does each setting iterate through each key independantly regardless of priority?

Yes, this is the way `pydantic-settings` works. 

I think the source of the problem is https://github.com/pydantic/pydantic-settings/blob/7e7ccdbc7b27d3f3d292d35a3b5033ef740fd6f7/pydantic_settings/sources.py#L2035-L2038

I created https://github.com/pydantic/pydantic-settings/pull/415 to fix the problem. Can you confirm the fix?

**Comment by DavidRR-F** [comment] 2024-09-20 13:32
Great! I have tested, yes this resolves the issue

**Comment by hramezani** [comment] 2024-09-20 13:34
Thank you for your quick feedback! I merged the PR and it will be released in the next release.

**Closed** 2024-09-20 13:33 UTC
Labels: bug
