### ISSUE TITLE
Pydantic 2.6.0 breaks pathlib validation against `str | os.PathLike`

### ISSUE THREAD

**Issue by ian-activeloop** [pydantic/pydantic-settings#456] opened 2024-10-23 20:29 UTC
I'm trying to make use of a project that has `paper-qa` hardlocked to `v5.0.10` but the moment I try to update individual settings object returned form its `get_settings()` method I run into pydantic validation errors on 2 fields (shown below, linking to lines of specific version used) that are typed as `str | os.PathLike`. This was working for my colleagues and I last week, but after a couple of us redid our venvs we got the `pydantic-settings==2.6.0` version, and for those of us on that version the `paper-qa` settings outright break. When we compared relevant version numbers with a colleague that did not have that validation issue we discovered they were still on `pydantic-settings==2.5.2`, and upon reverting to that version all of our path validation errors stopped and we were able to run `paper-qa`. As `2.6.0` was a "minor" release, we do not expect breaking behavior to occur.

https://github.com/Future-House/paper-qa/blob/v5.0.10/paperqa/settings.py#L413-L419
https://github.com/Future-House/paper-qa/blob/v5.0.10/paperqa/settings.py#L440-L445

**Comment by hramezani** [comment] 2024-10-23 21:59
Thanks @ian-activeloop  for reporting this issue.

This is a duplicate of https://github.com/pydantic/pydantic-settings/issues/445 and caused by https://github.com/pydantic/pydantic-settings/commit/76ba2c69c6bc77e96192aa460418b465f4b6782a.

please follow the original issue

**Comment by hramezani** [comment] 2024-11-01 11:04
This has been fixed in [pydantic-settings 2.6.1](https://pypi.org/project/pydantic-settings/)

**Closed by hramezani** 2024-11-01 11:04 UTC
Labels: duplicate
