### ISSUE TITLE
Settings are loaded in a docker but not in Kubernetes

### ISSUE THREAD

**Issue by vkaramanis** [pydantic/pydantic-settings#208] opened 2024-01-16 04:14 UTC
I have a FastAPI implementation with Pydrantic settings to load Environmental Variables.
I have made a docker image and run it in docker and all worked fine, but when I load the same image in a k8s cluster, I get the following error:

```python
 Traceback (most recent call last):                                                                                                  
   File "/tmp/api/./src/main.py", line 3, in <module>                                                                                
     from core.dependencies.settings import settings                                                                                 
   File "/tmp/api/src/core/dependencies/settings.py", line 70, in <module>                                                           
     settings = Settings()                                                                                                           
                ^^^^^^^^^^                                                                                                           
   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/main.py", line 72, in __init__                                    
     **__pydantic_self__._settings_build_values(                                                                                     
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                     
   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/main.py", line 160, in _settings_build_values                     
     return deep_update(*reversed([source() for source in sources]))                                                                 
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                   
   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/main.py", line 160, in <listcomp>                                 
     return deep_update(*reversed([source() for source in sources]))                                                                 
                                   ^^^^^^^^                                                                                          
   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources.py", line 252, in __call__                                
     field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)                                        
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources.py", line 426, in prepare_field_value                     
     env_val_built = self.explode_env_vars(field_name, field, self.env_vars)                                                         
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                         
   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources.py", line 527, in explode_env_vars                        
     env_var = env_var.setdefault(key, {})                                                                                           
               ^^^^^^^^^^^^^^^^^^                                                                                                    
 AttributeError: 'str' object has no attribute 'setdefault' 
```
I searched, but I haven't really found any solution on this.
I use python 3.11

code:

```python
from dotenv import find_dotenv
from pydantic import BaseModel
from pydantic_settings import BaseSettings, SettingsConfigDict

class PostgreSQL(BaseModel):
    host: str | None = None
    port: int = 5432
    user: str | None = None
    password: str | None = None
    database: str | None = None

class JWT(BaseModel):
    key: str = ""
    algorithm: str = "HS256"


class Authorization(BaseModel):
    basic: bool = False
    bearer: bool = False
    jwt: JWT = JWT()


class Api(BaseModel):
    host: str = "127.0.0.1"
    port: int = 3000
    sessionTimeout: int = 1800
    authorization: Authorization = Authorization()


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_nested_delimiter="_",
        env_file=find_dotenv(),
        env_file_encoding="utf-8",
        secrets_dir="/run/secrets",
        extra="ignore",
    )

    api: Api = Api()
    postgresql: PostgreSQL = PostgreSQL()


settings = Settings()
```

**Comment by hramezani** [comment] 2024-01-16 09:15
Thanks @vkaramanis for reporting this.

Please let us know your current pydantic-settings version. ( I think it is the latest version 2.1.0)

Could you provide your environment variables values? It would be great to fetch them by connecting to the container and running `env` command there.

**Comment by vkaramanis** [comment] 2024-01-16 17:11
@hramezani thanks for the reply, yes I am using 2.1.0

 After your comment, I found the problem. k8s was rewriting some of my env vars because they were present in other services on the same namespace.
For example: POSTGRESQL_PORT=tcp://10.152.183.174:5432 (I cannot share all my vars)

Although I checked some of my vars I didn't check all of them, and it was slipped, sorry for that (stupid).

So I added a prefix to all of them from SettingsConfigDict and now it runs smoothly.

However, as a side note, I still do not understand why it raises this error.

**Comment by hramezani** [comment] 2024-01-16 18:00
Thanks @vkaramanis for updating.

Yeah, that's weird for me. that's why I asked you to provide your env variables.
I need a way to reproduce the problem. So, I don't know what is the reason.

I close the issue for now. but feel free to reopen it or report a new issue if you face the problem again or find a way to reproduce the problem.

**Closed by hramezani** 2024-01-16 18:00 UTC
