### ISSUE TITLE
env_prefix prevents env_file from working

### ISSUE THREAD

**Issue by red8888** [pydantic/pydantic-settings#215] opened 2024-01-22 19:30 UTC
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Assuming this is a bug because I found nothing in the docs explaining this behavior.

Spent forever trying to understand why env_file wasn't working. Commenting out env_prefix cause env_file to start working. This can't be by design right? I should be able to define both.

### Example Code

```Python
model_config = SettingsConfigDict(
        env_file=[
            "my.env",
        ],
        # When uncommented pydantic does not attempt to load any files defined in env_file 
        # env_prefix="my_app_",
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 19 2023, 20:23:36) [GCC 10.2.1 20210110]
                     platform: Linux-6.5.11-linuxkit-x86_64-with-glibc2.31
             related packages: pydantic-settings-2.1.0 mypy-1.8.0 typing_extensions-4.9.0
```

Edit
===
I found the issue. The issue is that setting `env_prefix` causes pydantic to ignore non-prefixed env vars defined in you dotenv files.

I was expecting it to fail because I had un-prefixed vars defined in mysettings.env for example:

    MY_SETTING_ONE=ksjdlksjd
    MY_SETTING_TWO=zzzzzzz

Changing those to this worked:

    MY_APP_MY_SETTING_ONE=ksjdlksjd
    MY_APP_MY_SETTING_TWO=zzzzzzz

So I think the bug is pydantic should not be ignoring un-prefixed fields in dotenv files.

Because while this correctly throws `Extra inputs are not permitted`:

    MY_APP_SETTING_THAT_DOESNT_EXIST=ksjdlksjd

This throws no errors at all:

    SETTING_THAT_DOESNT_EXIST=ksjdlksjd

**Comment by hramezani** [comment] 2024-01-23 12:04
Thanks @red8888 for reporting this.
It is an intended behavior. dotenv source settings inherited from env source settings and it only loads env variables from file.

it has to be consistent with env source settings. pydantic-settings has the same behavior in env variables.

**Comment by hramezani** [comment] 2024-01-23 16:05
Thanks @red8888 for reporting this.

Agree, that is probably a bug.

**Comment by kjithin** [comment] 2024-01-24 16:16
Hi @hramezani ,

I would like to work on this issue.

**Comment by hramezani** [comment] 2024-01-24 16:34
Thanks @kjithin, I've assigned it to you!

**Comment by kjithin** [comment] 2024-01-25 13:04
Thanks @hramezani. I've submitted a pull request addressing this issue. Kindly review and share your feedback.

**Closed** 2024-01-25 15:07 UTC
Labels: bug
