### ISSUE TITLE
Validation is only performed during debugging

### ISSUE THREAD

**Issue by BabakAmini** [pydantic/pydantic-settings#446] opened 2024-10-18 09:58 UTC
I have an environment file that contains several key variables necessary for my application's proper functioning. However, I accidentally added a comment in front of one of these variables, which caused some confusion during debugging. While my code runs smoothly without any apparent issues, I encounter a validation error related to that specific variable when I debug it.

Here are sample codes:

```python
# config.py
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Config(BaseSettings):
    ENVIRONMENT: Literal['debug', 'testing', 'production'] = 'debug'

    model_config = SettingsConfigDict(
        env_file='.env',,
        env_ignore_empty=True,
        extra='ignore',
    )

config = Config()
```

``` python
# main.py
from config import config
```

``` python
# .env
ENVIRONMENT=debug   # some comments here
```

Enclosing the `debug` statement in double quotes doesn't seem to resolve the issue, but removing the comment does.

Am I missing something?

**Comment by hramezani** [comment] 2024-10-18 12:02
Thanks @BabakAmini for reporting this issue.

What error did you get?

**Comment by hramezani** [comment] 2024-10-18 12:23
which version of `pydantic-settings` are you using?

**Comment by hramezani** [comment] 2024-10-18 12:59
@BabakAmini 

I tested your provided example on the main and couldn't reproduce the problem. probably you have some wrong value somewhere. like in environment variables. Could you check your environment variables?

**Comment by hramezani** [comment] 2024-10-18 15:34
@BabakAmini what are the `run` and `debug` modes?

Please test your example above with another field name to make sure there is nothing to override the value. like:

```py
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Config(BaseSettings):
    MY_TEST_FIELD: Literal['debug', 'testing', 'production'] = 'debug'

    model_config = SettingsConfigDict(
        env_file='.env',
        env_ignore_empty=True,
        extra='ignore',
    )

print(Config())
```

```bash
#.env
MY_TEST_FIELD=debug   # some comments here
```

**Comment by hramezani** [comment] 2024-10-18 15:49
@BabakAmini 
I am not running the code in vscode but couldn't reproduce the problem.

Could you do me a favor and some how try to reproduce the problem outside of vscode?

**Comment by hramezani** [comment] 2024-10-18 16:14
Not sure what is the problem in vs code. I am not an expert on vs code.

I closed this issue but feel free to re-open it if you think this is still a problem.

**Closed as completed by hramezani** 2024-10-18 16:14 UTC
Labels: unconfirmed
